"""
mage deployer implementation.

Generated by: python -m metaflow_orchestrator_kit.scaffold mage

OrchestratorCapabilities contract (DO NOT remove these comments):

  Cap.RUN_PARAMS     — run_params MUST be a list, not a tuple.
                       Click returns tuples for multi-value options.
                       Always convert with list() before passing to the scheduler API.

  Cap.PROJECT_BRANCH — --branch MUST be forwarded to every step subprocess.
                       @project reads branch_name from --branch at step runtime,
                       not just at compile time.

  Cap.CONFIG_EXPR    — METAFLOW_FLOW_CONFIG_VALUE MUST be injected into every
                       container/subprocess environment.
                       @config and @project use this env var to reconstruct the
                       config dict at task runtime.  Without it, tasks run with
                       empty/default config and @project name is wrong.

  Cap.RETRY          — retry_count MUST be derived from the scheduler's native
                       attempt number.  DO NOT hardcode retry_count=0.
                       Examples:
                         AWS Batch:   int(os.environ.get("AWS_BATCH_JOB_ATTEMPT", "0"))
                         Kubernetes:  derived from pod restartCount or annotation
                         Airflow:     context["ti"].try_number - 1

  Cap.FROM_DEPLOYMENT — from_deployment() must handle dotted identifiers
                        (project.branch.FlowName).  Use only the last component:
                        identifier.split(".")[-1]

See metaflow_orchestrator_kit.capabilities for the full list.
"""

import json
import os
import sys
from typing import ClassVar, Dict, List, Optional, Type

from metaflow.runner.deployer_impl import DeployerImpl

# REQUIRED: declare which capabilities this orchestrator supports.
from metaflow_orchestrator_kit import Cap, REQUIRED

SUPPORTED_CAPABILITIES = REQUIRED  # TODO: add optional caps you implement


# ---------------------------------------------------------------------------
# Compile-time helpers — called when create() is invoked, NOT at step runtime.
# ---------------------------------------------------------------------------


def _get_flow_config_value(flow) -> Optional[str]:
    """
    Extract the serialized config dict from the flow at compile time.

    REQUIRED (Cap.CONFIG_EXPR): Bake this into the workflow definition and inject
    as METAFLOW_FLOW_CONFIG_VALUE into every step subprocess env.
    Without it, @config and @project decorators use empty/default config at
    task runtime and current.branch_name is wrong.
    """
    try:
        from metaflow.flowspec import FlowStateItems
        flow_configs = flow._flow_state[FlowStateItems.CONFIGS]
        config_env = {
            name: value
            for name, (value, _is_plain) in flow_configs.items()
            if value is not None
        }
        if config_env:
            return json.dumps(config_env)
    except Exception:
        pass
    return None


def _get_datastore_sysroot() -> str:
    """
    Capture METAFLOW_DATASTORE_SYSROOT_LOCAL at compile (deploy) time.

    REQUIRED: Bake this into the workflow so workers write metadata to the
    same location the deployer reads from, even when the worker starts with
    a different (or absent) sysroot env var.
    """
    return os.environ.get("METAFLOW_DATASTORE_SYSROOT_LOCAL", os.path.expanduser("~"))


def _get_environment_type(environment) -> str:
    """
    Extract the environment type string from the Metaflow environment object.

    REQUIRED for @conda: pass --environment conda (or local) to every step
    subprocess so the correct Python interpreter is used.
    """
    return getattr(environment, "TYPE", "local")


class MageDeployerImpl(DeployerImpl):
    """
    Deployer implementation for mage.

    Compiles the flow into a mage workflow definition and submits it
    to the mage scheduler.
    """

    TYPE: ClassVar[Optional[str]] = "mage"

    def __init__(self, deployer_kwargs: Dict, **kwargs):
        # deployer_kwargs contains keyword arguments from Deployer(flow_file).mage(...)
        # Store it before calling super().__init__ so the property works.
        self._deployer_kwargs = deployer_kwargs
        super().__init__(**kwargs)
        # TODO: SCHEDULER API — extract mage-specific options from deployer_kwargs, e.g.:
        #   self.host = deployer_kwargs.get("host", "http://localhost:8080")
        #   self.namespace = deployer_kwargs.get("namespace", "default")

    @property
    def deployer_kwargs(self) -> Dict:
        return self._deployer_kwargs

    @staticmethod
    def deployed_flow_type() -> Type:
        from mage_objects import MageDeployedFlow
        return MageDeployedFlow

    def create(self, **kwargs):
        return self._create(self.deployed_flow_type(), **kwargs)

    def _compile_workflow(self, flow, graph, environment, **kwargs) -> dict:
        """
        Compile the flow into a mage workflow definition (JSON/YAML/etc).

        Called by create() with the loaded flow objects.  All compile-time
        constants MUST be captured here, NOT at step execution time.
        """
        # Capture compile-time constants — baked into the workflow definition.
        flow_config_value = _get_flow_config_value(flow)
        datastore_sysroot = _get_datastore_sysroot()
        environment_type = _get_environment_type(environment)
        flow_file = self.flow_file
        flow_name = flow.__class__.__name__

        # Extract @project branch if set
        branch = self._deployer_kwargs.get("branch") or None

        # Build the required environment for every step subprocess.
        # ALL of these must be present in every step container/process.
        required_env = {
            # REQUIRED (Cap.CONFIG_EXPR): propagate config to step subprocesses.
            # Without this, @config/@project decorators use empty/default values.
            "METAFLOW_FLOW_CONFIG_VALUE": flow_config_value or "",

            # REQUIRED: sysroot pinned at compile time.
            "METAFLOW_DATASTORE_SYSROOT_LOCAL": datastore_sysroot,

            # REQUIRED: Metaflow metadata service URL reachable from the worker.
            "METAFLOW_SERVICE_URL": os.environ.get("METAFLOW_SERVICE_URL", ""),
            "METAFLOW_SERVICE_INTERNAL_URL": os.environ.get(
                "METAFLOW_SERVICE_INTERNAL_URL",
                os.environ.get("METAFLOW_SERVICE_URL", ""),
            ),

            # REQUIRED: PATH so conda/virtualenv binaries are found.
            "PATH": os.environ.get("PATH", ""),
        }

        # TODO: SCHEDULER API — build the actual workflow definition here.
        # The workflow must encode:
        #   1. The DAG structure (from `graph`)
        #   2. For each step: the command (see _build_step_command below)
        #   3. required_env injected into every step container/process env
        #   4. branch stored so it can be passed to each step command

        return {
            "flow_name": flow_name,
            "flow_file": flow_file,
            "environment_type": environment_type,
            "datastore_sysroot": datastore_sysroot,
            "flow_config_value": flow_config_value,
            "branch": branch,
            "required_env": required_env,
            # TODO: SCHEDULER API — add scheduler-specific fields
        }

    def _build_step_command(
        self,
        step_name: str,
        run_id: str,
        task_id: str,
        input_paths: str,
        branch: Optional[str] = None,
        retry_count: int = 0,  # REQUIRED (Cap.RETRY): derive from scheduler attempt
        environment_type: str = "local",
        flow_file: Optional[str] = None,
    ) -> List[str]:
        """
        Build the command list to execute one Metaflow step.

        REQUIRED (Cap.PROJECT_BRANCH):
            --branch MUST be included when branch is not None.
            @project reads branch_name from --branch at step runtime.
            Omitting --branch causes current.branch_name to be empty.

        REQUIRED (Cap.RETRY):
            retry_count MUST come from the scheduler native attempt counter.
            DO NOT leave retry_count=0.
            Examples by scheduler:
              AWS Batch:   int(os.environ.get("AWS_BATCH_JOB_ATTEMPT", "0"))
              Kubernetes:  from pod annotation or restart count
              Airflow:     context["ti"].try_number - 1
              Prefect:     ctx.task_run.run_count - 1

        REQUIRED (environment_type):
            Pass --environment so the correct Python is used for @conda flows.

        OPTIONAL (Cap.CONDA) — two approaches depending on executor type:

        APPROACH A — subprocess-based orchestrators (standard):
            Pass --environment conda (or whatever environment_type is).
            Metaflow's built-in task runner calls conda_decorator.runtime_init()
            automatically when the step subprocess starts.  runtime_init()
            extracts the code package into a temp dir and adds it to PYTHONPATH.
            No additional work needed.  This is what the code below does.

        APPROACH B — in-process executors (Dagster execute_job, Windmill sync,
            Mage, or any orchestrator that runs steps without re-entering the
            Metaflow subprocess runtime):
            runtime_init() is NEVER called, so:
              - _metaflow_home is None
              - The code package is never extracted
              - conda-installed packages are NOT on PYTHONPATH
              - Steps fail with ModuleNotFoundError for any conda package

            FIX: use "conda run -n <env_name>" to wrap the step command.
            conda run activates the named environment before launching the
            process, setting PYTHONPATH, sys.executable, and native library
            paths automatically.

            If your orchestrator uses Approach B, replace the cmd construction
            below with:
                if environment_type == "conda" and conda_env_name:
                    cmd = [
                        "conda", "run", "--no-capture-output",
                        "-n", conda_env_name,
                        "python",
                    ]
                else:
                    cmd = [sys.executable]

            See: metaflow/plugins/pypi/conda_decorator.py CondaStepDecorator.runtime_init()
        """
        flow_file = flow_file or self.flow_file
        cmd = [
            sys.executable, flow_file,
            "--no-pylint",
            "--environment", environment_type,
            "--metadata", "service",
        ]

        if branch:
            # REQUIRED (Cap.PROJECT_BRANCH): DO NOT REMOVE — forward --branch to
            # every step subprocess so @project reads the correct branch_name.
            cmd += ["--branch", branch]

        cmd += [
            "step", step_name,
            "--run-id", run_id,
            "--task-id", task_id,
            "--retry-count", str(retry_count),  # TODO: SCHEDULER API — replace 0 with scheduler attempt
            "--input-paths", input_paths,
        ]

        return cmd
