"""
mage CLI group for Metaflow.

Generated by: python -m metaflow_orchestrator_kit.scaffold mage

This group is registered via mfextinit_mage.py so that
`python flow.py mage ...` works after the extension is installed.
"""

import click


@click.group()
def cli():
    """Commands for managing mage deployments."""
    pass


@cli.command()
@click.option("--tags", multiple=True, help="Tags to apply to the deployment.")
@click.option(
    "--deployer-attribute-file",
    default=None,
    help="Internal: path to write deployment attributes JSON.",
)
def create(tags, deployer_attribute_file):
    """Deploy the flow to mage."""
    # REQUIRED: after successful deployment, write a JSON file to
    # deployer_attribute_file with at least:
    #   {"name": "<workflow_id>", "flow_name": "<FlowClass>"}
    # This is how the Deployer API learns the deployed workflow name.
    #
    # TODO: SCHEDULER API — compile workflow definition and submit to mage
    raise NotImplementedError("create() not yet implemented")


@cli.command()
def delete():
    """Remove a mage deployment."""
    raise NotImplementedError("delete() not yet implemented")


@cli.command()
def list():
    """List mage deployments for this flow."""
    raise NotImplementedError("list() not yet implemented")


@cli.command()
@click.option("--name", required=True, help="Deployment name to trigger.")
@click.option("--run-param", multiple=True, help="Flow parameter as key=value.")
@click.option(
    "--deployer-attribute-file",
    default=None,
    help="Internal: path to write trigger attributes JSON.",
)
def trigger(name, run_param, deployer_attribute_file):
    """Trigger a run of a deployed mage workflow."""
    # REQUIRED (Cap.RUN_PARAMS): run_param arrives as a tuple from Click.
    # Convert to list before using:
    run_params = list(run_param)

    # TODO: SCHEDULER API — trigger the workflow named `name` with `run_params`
    # After triggering, write a JSON file to deployer_attribute_file with at least:
    #   {"pathspec": "<FlowName>/<run_id>"}
    raise NotImplementedError("trigger() not yet implemented")
