"""
mage DeployedFlow and TriggeredRun objects.

Generated by: python -m metaflow_orchestrator_kit.scaffold mage
"""

import os
from typing import Any, ClassVar, Dict, List, Optional

from metaflow.runner.deployer import DeployedFlow, TriggeredRun


class MageTriggeredRun(TriggeredRun):
    """Represents a single triggered execution of a mage workflow."""

    @property
    def status(self) -> Optional[str]:
        """
        Return the current run status.

        MUST return one of: None, "RUNNING", "SUCCEEDED", "FAILED", "TIMED_OUT",
        "ABORTED" (case-insensitive check in wait_for_deployed_run).

        Return None when the run has not started yet.
        """
        # TODO: SCHEDULER API — query mage for the current execution status
        raise NotImplementedError

    def terminate(self, **kwargs) -> bool:
        """Terminate the running execution. Return True if successful."""
        # TODO: SCHEDULER API — call mage API to stop the execution
        raise NotImplementedError


class MageDeployedFlow(DeployedFlow):
    """Represents a deployed mage workflow (analogous to a DAG or state machine)."""

    TYPE: ClassVar[Optional[str]] = "mage"

    def trigger(
        self,
        run_params: Optional[List[str]] = None,
        **kwargs: Any,
    ) -> MageTriggeredRun:
        """
        Trigger a new run of the deployed workflow.

        REQUIRED (Cap.RUN_PARAMS): run_params MUST be a list, not a tuple.
        Click returns tuples for multi-value options; always convert:
            run_params = list(run_params) if run_params else []
        Passing a tuple raises TypeError inside most scheduler client libraries.
        """
        # REQUIRED (Cap.RUN_PARAMS): must be list, not tuple — DO NOT REMOVE
        run_params = list(run_params) if run_params else []

        # TODO: SCHEDULER API — call mage API to start a new execution.
        # Steps to complete:
        #   1. Generate a Metaflow run_id (e.g. "mage-" + str(uuid.uuid4())[:12])
        #   2. Trigger the mage execution, forwarding run_params as flow parameters
        #   3. Return a MageTriggeredRun with the pathspec set:
        #        pathspec = f"{self.deployer.flow_name}/{run_id}"
        raise NotImplementedError

    @classmethod
    def from_deployment(cls, identifier: str, **kwargs) -> "MageDeployedFlow":
        """
        Recover a previously deployed workflow by its identifier.

        REQUIRED (Cap.FROM_DEPLOYMENT):
            identifier may be a dotted name (project.branch.FlowName).
            Use only the last component as the Python class name:
                flow_name = identifier.split(".")[-1]
            Using the full dotted string as a class name raises SyntaxError.
        """
        # REQUIRED (Cap.FROM_DEPLOYMENT): handle dotted names — DO NOT REMOVE
        flow_name = identifier.split(".")[-1]

        # TODO: SCHEDULER API — look up the mage workflow by identifier
        # and return a MageDeployedFlow instance.
        raise NotImplementedError
